<a href="https://colab.research.google.com/github/joaocanaslopes/ML_project-/blob/main/Data_Cleaning_and_Integration_of_Agro_Climatic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

### Precipitation Data for Faro

In [2]:
df_prec_faro = pd.read_csv('/content/prec-Faro.csv')
display(df_prec_faro.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    52 non-null     int64
 1   Jan     51 non-null     float64
 2   Feb     51 non-null     float64
 3   Mar     51 non-null     float64
 4   Apr     51 non-null     float64
 5   May     51 non-null     float64
 6   Jun     51 non-null     float64
 7   Jul     51 non-null     float64
 8   Aug     51 non-null     float64
 9   Sep     51 non-null     float64
 10  Oct     52 non-null     float64
 11  Nov     52 non-null     float64
 12  Dec     52 non-null     float64
 13  Spring  51 non-null     float64
 14  Summer  51 non-null     float64
 15  Autumn  51 non-null     float64
 16  Annual  51 non-null     float64
 17  Winter  50 non-null     float64
dtypes: float64(17), int64(1)
memory usage: 7.4 KB

None

### Temperature Data for Beja

In [3]:
df_temp_beja_raw = pd.read_csv('/content/temp-Beja-raw.csv')
display(df_temp_beja_raw.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1415 entries, 0 to 1414
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1415 non-null   object
 1   tmax    1415 non-null   float64
 2   tmin    1415 non-null   float64
 3   tmed    1415 non-null   float64
dtypes: float64(3), object(1)
memory usage: 44.3+ KB

None

### Temperature Data for Faro

In [4]:
df_temp_faro = pd.read_csv('/content/temp-Faro.csv')
display(df_temp_faro.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 635 entries, 0 to 634
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    635 non-null    object
 1   tmax    635 non-null    float64
 2   tmin    635 non-null    float64
 3   tmed    635 non-null    float64
dtypes: float64(3), object(1)
memory usage: 20.0+ KB

None

### Precipitation Data for Beja

In [5]:
df_prec_beja_raw = pd.read_csv('/content/prec-Beja-raw.csv')
display(df_prec_beja_raw.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    118 non-null    int64
 1   Jan     118 non-null    float64
 2   Feb     118 non-null    float64
 3   Mar     118 non-null    float64
 4   Apr     118 non-null    float64
 5   May     118 non-null    float64
 6   Jun     118 non-null    float64
 7   Jul     118 non-null    float64
 8   Aug     118 non-null    float64
 9   Sep     118 non-null    float64
 10  Oct     118 non-null    float64
 11  Nov     118 non-null    float64
 12  Dec     118 non-null    float64
 13  Spring  118 non-null    float64
 14  Summer  118 non-null    float64
 15  Autumn  118 non-null    float64
 16  Annual  118 non-null    float64
 17  Winter  117 non-null    float64
dtypes: float64(17), int64(1)
memory usage: 16.7 KB

None

In [6]:
# Filter df_prec_faro (Precipitation Faro)
df_prec_faro_filtered = df_prec_faro[df_prec_faro['year'] >= 2000]
print("\n--- Filtered Precipitation Faro (df_prec_faro_filtered) ---")
display(df_prec_faro_filtered.head())
display(df_prec_faro_filtered.info())

# Filter df_temp_beja_raw (Temperature Beja)
# Reload df_temp_beja_raw to ensure it's defined
df_temp_beja_raw = pd.read_csv('/content/temp-Beja-raw.csv')
df_temp_beja_raw['date'] = pd.to_datetime(df_temp_beja_raw['date'], format='%m/%Y')
df_temp_beja_raw_filtered = df_temp_beja_raw[df_temp_beja_raw['date'].dt.year >= 2000]
print("\n--- Filtered Temperature Beja (df_temp_beja_raw_filtered) ---")
display(df_temp_beja_raw_filtered.head())
display(df_temp_beja_raw_filtered.info())

# Filter df_temp_faro (Temperature Faro)
df_temp_faro['date'] = pd.to_datetime(df_temp_faro['date'], format='%m/%Y')
df_temp_faro_filtered = df_temp_faro[df_temp_faro['date'].dt.year >= 2000]
print("\n--- Filtered Temperature Faro (df_temp_faro_filtered) ---")
display(df_temp_faro_filtered.head())
display(df_temp_faro_filtered.info())

# Filter df_prec_beja_raw (Precipitation Beja)
df_prec_beja_raw_filtered = df_prec_beja_raw[df_prec_beja_raw['year'] >= 2000]
print("\n--- Filtered Precipitation Beja (df_prec_beja_raw_filtered) ---")
display(df_prec_beja_raw_filtered.head())
display(df_prec_beja_raw_filtered.info())

--- Filtered Precipitation Faro (df_prec_faro_filtered) ---

,year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Spring,Summer,Autumn,Annual,Winter
34,2000,78.2,4.4,23.5,109.8,56.7,0.0,0.0,0.1,17.5,7.8,36.1,139.2,190.0,0.1,61.4,473.3,106.1
35,2001,72.6,40.4,115.2,0.0,15.7,0.0,0.1,0.0,115.3,51.5,93.5,188.4,130.9,0.1,260.3,692.7,252.2
36,2002,38.6,6.2,51.3,40.4,19.0,0.4,0.0,0.2,95.4,91.8,81.6,71.7,110.7,0.6,268.8,496.6,233.2
37,2003,37.0,57.6,57.4,77.6,4.5,1.9,0.0,0.6,0.0,122.5,85.5,78.1,139.5,2.5,208.0,522.7,166.3
38,2004,21.4,112.2,38.8,10.9,25.8,0.0,0.0,2.2,1.7,37.4,22.5,41.9,75.5,2.2,61.6,314.8,211.7

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 34 to 51
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    18 non-null     int64
 1   Jan     17 non-null     float64
 2   Feb     17 non-null     float64
 3   Mar     17 non-null     float64
 4   Apr     17 non-null     float64
 5   May     17 non-null     float64
 6   Jun     17 non-null     float64
 7   Jul     17 non-null     float64
 8   Aug     17 non-null     float64
 9   Sep     17 non-null     float64
 10  Oct     18 non-null     float64
 11  Nov     18 non-null     float64
 12  Dec     18 non-null     float64
 13  Spring  17 non-null     float64
 14  Summer  17 non-null     float64
 15  Autumn  17 non-null     float64
 16  Annual  17 non-null     float64
 17  Winter  17 non-null     float64
dtypes: float64(17), int64(1)
memory usage: 2.7 KB

None

--- Filtered Temperature Beja (df_temp_beja_raw_filtered) ---

           date  tmax  tmin   tmed
1187 2000-01-01  13.1   3.5   8.30
1188 2000-02-01  18.2   7.0  12.60
1189 2000-03-01  20.5   8.6  14.55
1190 2000-04-01  16.8   8.9  12.85
1191 2000-05-01  22.6  12.3  17.45

<class 'pandas.core.frame.DataFrame'>
Index: 228 entries, 1187 to 1414
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    228 non-null    datetime64[ns]
 1   tmax    228 non-null    float64
 2   tmin    228 non-null    float64
 3   tmed    228 non-null    float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 8.9 KB

None

--- Filtered Temperature Faro (df_temp_faro_filtered) ---

          date   tmax   tmin   tmed
408 2000-01-01  15.10   6.95  11.02
409 2000-02-01  19.22   9.78  14.50
410 2000-03-01  19.85  11.68  15.76
411 2000-04-01  18.26  11.54  14.90
412 2000-05-01  22.43  15.59  19.01

<class 'pandas.core.frame.DataFrame'>
Index: 227 entries, 408 to 634
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    227 non-null    datetime64[ns]
 1   tmax    227 non-null    float64
 2   tmin    227 non-null    float64
 3   tmed    227 non-null    float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 8.9 KB

None

--- Filtered Precipitation Beja (df_prec_beja_raw_filtered) ---

,year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Spring,Summer,Autumn,Annual,Winter
99,2000,10.6,4.0,26.2,152.0,96.9,5.5,0.0,0.5,4.1,43.1,90.1,263.6,275.1,6.0,137.3,696.6,69.8
100,2001,104.2,94.5,104.8,1.6,56.5,5.9,0.9,0.1,54.0,128.6,43.9,74.8,162.9,6.9,226.5,669.8,462.3
101,2002,45.1,11.8,94.4,66.1,20.2,6.1,0.5,0.0,92.8,51.8,78.6,105.1,180.7,6.6,223.2,572.5,131.7
102,2003,59.6,67.3,31.8,81.2,12.0,1.5,0.0,0.0,4.8,188.0,87.4,53.4,125.0,1.5,280.2,587.0,232.0
103,2004,41.1,61.1,29.9,13.1,23.0,0.0,0.0,10.1,20.2,69.8,20.2,27.8,66.0,10.1,110.2,316.3,155.6

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 99 to 117
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    19 non-null     int64
 1   Jan     19 non-null     float64
 2   Feb     19 non-null     float64
 3   Mar     19 non-null     float64
 4   Apr     19 non-null     float64
 5   May     19 non-null     float64
 6   Jun     19 non-null     float64
 7   Jul     19 non-null     float64
 8   Aug     19 non-null     float64
 9   Sep     19 non-null     float64
 10  Oct     19 non-null     float64
 11  Nov     19 non-null     float64
 12  Dec     19 non-null     float64
 13  Spring  19 non-null     float64
 14  Summer  19 non-null     float64
 15  Autumn  19 non-null     float64
 16  Annual  19 non-null     float64
 17  Winter  19 non-null     float64
dtypes: float64(17), int64(1)
memory usage: 2.8 KB

None

 ## Juntar dados da percipitação

Alentejo (Beja)

In [7]:
prec_beja = (
    df_prec_beja_raw_filtered[['year', 'Annual']]
    .copy()
)

prec_beja['region'] = 'Alentejo'

prec_beja.rename(
    columns={'Annual':'precipitation_mm'},
    inplace=True
)

Algarve (Faro)

In [8]:
prec_faro = (
    df_prec_faro_filtered[['year', 'Annual']]
    .copy()
)

prec_faro['region'] = 'Algarve'

prec_faro.rename(
    columns={'Annual':'precipitation_mm'},
    inplace=True
)

Juntar precipitação

In [9]:
precipitation = pd.concat(
    [prec_beja, prec_faro],
    ignore_index=True
)

display(precipitation.head(40))

    year  precipitation_mm    region
0   2000             696.6  Alentejo
1   2001             669.8  Alentejo
2   2002             572.5  Alentejo
3   2003             587.0  Alentejo
4   2004             316.3  Alentejo
5   2005             339.1  Alentejo
6   2006             575.5  Alentejo
7   2007             349.8  Alentejo
8   2008             501.5  Alentejo
9   2009             483.8  Alentejo
10  2010             815.3  Alentejo
11  2011             656.8  Alentejo
12  2012             354.3  Alentejo
13  2013             443.5  Alentejo
14  2014             703.6  Alentejo
15  2015             415.0  Alentejo
16  2016             728.0  Alentejo
17  2017             434.1  Alentejo
18  2018             570.0  Alentejo
19  2000             473.3   Algarve
20  2001             692.7   Algarve
21  2002             496.6   Algarve
22  2003             522.7   Algarve
23  2004             314.8   Algarve
24  2005             368.0   Algarve
25  2006             582.9   Algarve
26  2007             400.3   Algarve
27  2008             485.4   Algarve
28  2009             504.6   Algarve
29  2010             718.0   Algarve
30  2011             536.7   Algarve
31  2012             306.2   Algarve
32  2014               NaN   Algarve
33  2015             343.0   Algarve
34  2016             475.7   Algarve
35  2017             316.1   Algarve
36  2018             499.1   Algarve

## Juntar dados da temperatura

Criar coluna ano:

In [10]:
df_temp_beja_raw_filtered['year'] = (
    df_temp_beja_raw_filtered['date']
    .dt.year
)

/tmp/ipykernel_22894/83720725.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp_beja_raw_filtered['year'] = (

Agregar os dados

In [11]:
temp_beja = (
    df_temp_beja_raw_filtered
    .groupby('year')
    .agg(
        mean_temp=('tmed', 'mean'),
        mean_tmax=('tmax', 'mean'),
        mean_tmin=('tmin', 'mean')
    )
    .reset_index()
)

Adicionar região:

In [12]:
temp_beja['region'] = 'Alentejo'

Agora o mesmo para Faro

In [13]:
df_temp_faro_filtered['year'] = (
    df_temp_faro_filtered['date']
    .dt.year
)

temp_faro = (
    df_temp_faro_filtered
    .groupby('year')
    .agg(
        mean_temp=('tmed', 'mean'),
        mean_tmax=('tmax', 'mean'),
        mean_tmin=('tmin', 'mean')
    )
    .reset_index()
)

temp_faro['region'] = 'Algarve'

/tmp/ipykernel_22894/3205852100.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp_faro_filtered['year'] = (

Juntar a temperatura das duas regioes

In [14]:
temperature = pd.concat(
    [temp_beja, temp_faro],
    ignore_index=True
)

display(temperature.head(40))

    year  mean_temp  mean_tmax  mean_tmin    region
0   2000  16.958333  22.758333  11.158333  Alentejo
1   2001  16.987500  22.550000  11.425000  Alentejo
2   2002  16.895833  22.558333  11.233333  Alentejo
3   2003  17.262500  23.016667  11.508333  Alentejo
4   2004  17.191667  23.375000  11.008333  Alentejo
5   2005  17.116667  23.501667  10.733333  Alentejo
6   2006  17.382500  23.446667  11.318333  Alentejo
7   2007  16.683333  22.789167  10.575000  Alentejo
8   2008  16.484167  22.689167  10.280833  Alentejo
9   2009  17.556667  23.753333  11.360000  Alentejo
10  2010  17.114167  22.856667  11.372500  Alentejo
11  2011  17.486667  23.405833  11.568333  Alentejo
12  2012  16.707500  22.904167  10.512500  Alentejo
13  2013  16.858333  22.819167  10.899167  Alentejo
14  2014  17.575000  23.528333  11.626667  Alentejo
15  2015  18.022500  24.487500  11.555833  Alentejo
16  2016  17.429167  23.700000  11.160000  Alentejo
17  2017  18.050833  24.865833  11.235000  Alentejo
18  2018  16.590000  22.610833  10.570000  Alentejo
19  2000  17.996667  21.965833  14.030000   Algarve
20  2001  18.151667  22.081667  14.221667   Algarve
21  2002  18.063333  22.085833  14.037500   Algarve
22  2003  18.254167  22.270000  14.240833   Algarve
23  2004  18.102500  22.287500  13.914167   Algarve
24  2005  17.800833  21.833333  13.770000   Algarve
25  2006  18.284167  22.260833  14.309167   Algarve
26  2007  17.945000  22.228333  13.660000   Algarve
27  2008  17.827500  21.990000  13.665000   Algarve
28  2009  18.386667  22.607500  14.165000   Algarve
29  2010  18.568333  22.326667  14.811667   Algarve
30  2011  18.880000  22.915833  14.842500   Algarve
31  2012  18.208333  22.550000  13.865833   Algarve
32  2013  18.198333  22.055833  14.341667   Algarve
33  2014  18.463333  22.436667  14.490833   Algarve
34  2015  18.776667  22.785000  14.765000   Algarve
35  2016  18.866667  22.862500  14.870833   Algarve
36  2017  18.641818  22.824545  14.454545   Algarve
37  2018  17.950000  21.969167  13.930000   Algarve

 ## Construir a tabela climática final

Agora fazemos o merge:

In [104]:
climate = pd.merge(
    precipitation,
    temperature,
    on=['year', 'region'],
    how='outer' # Changed from 'inner' to 'outer'
)

display(climate.head(40))

    year  precipitation_mm    region  mean_temp  mean_tmax  mean_tmin
0   2000             696.6  Alentejo  16.958333  22.758333  11.158333
1   2000             473.3   Algarve  17.996667  21.965833  14.030000
2   2001             669.8  Alentejo  16.987500  22.550000  11.425000
3   2001             692.7   Algarve  18.151667  22.081667  14.221667
4   2002             572.5  Alentejo  16.895833  22.558333  11.233333
5   2002             496.6   Algarve  18.063333  22.085833  14.037500
6   2003             587.0  Alentejo  17.262500  23.016667  11.508333
7   2003             522.7   Algarve  18.254167  22.270000  14.240833
8   2004             316.3  Alentejo  17.191667  23.375000  11.008333
9   2004             314.8   Algarve  18.102500  22.287500  13.914167
10  2005             339.1  Alentejo  17.116667  23.501667  10.733333
11  2005             368.0   Algarve  17.800833  21.833333  13.770000
12  2006             575.5  Alentejo  17.382500  23.446667  11.318333
13  2006             582.9   Algarve  18.284167  22.260833  14.309167
14  2007             349.8  Alentejo  16.683333  22.789167  10.575000
15  2007             400.3   Algarve  17.945000  22.228333  13.660000
16  2008             501.5  Alentejo  16.484167  22.689167  10.280833
17  2008             485.4   Algarve  17.827500  21.990000  13.665000
18  2009             483.8  Alentejo  17.556667  23.753333  11.360000
19  2009             504.6   Algarve  18.386667  22.607500  14.165000
20  2010             815.3  Alentejo  17.114167  22.856667  11.372500
21  2010             718.0   Algarve  18.568333  22.326667  14.811667
22  2011             656.8  Alentejo  17.486667  23.405833  11.568333
23  2011             536.7   Algarve  18.880000  22.915833  14.842500
24  2012             354.3  Alentejo  16.707500  22.904167  10.512500
25  2012             306.2   Algarve  18.208333  22.550000  13.865833
26  2013             443.5  Alentejo  16.858333  22.819167  10.899167
27  2013               NaN   Algarve  18.198333  22.055833  14.341667
28  2014             703.6  Alentejo  17.575000  23.528333  11.626667
29  2014               NaN   Algarve  18.463333  22.436667  14.490833
30  2015             415.0  Alentejo  18.022500  24.487500  11.555833
31  2015             343.0   Algarve  18.776667  22.785000  14.765000
32  2016             728.0  Alentejo  17.429167  23.700000  11.160000
33  2016             475.7   Algarve  18.866667  22.862500  14.870833
34  2017             434.1  Alentejo  18.050833  24.865833  11.235000
35  2017             316.1   Algarve  18.641818  22.824545  14.454545
36  2018             570.0  Alentejo  16.590000  22.610833  10.570000
37  2018             499.1   Algarve  17.950000  21.969167  13.930000

## Guardar

In [16]:
climate.to_csv(
    'climate_final.csv',
    index=False
)

## Ler o doc do ine

In [17]:
import pandas as pd

prod = pd.read_csv("/content/prod.csv")
irr = pd.read_csv("/content/irrigacao.csv")

## ver a estrutura

In [18]:
prod.head(100)

,Período de referência dos dados,Localização geográfica (Região agrária),Espécie,Superfície das principais culturas agrícolas (ha) por Localização geográfica (Região agrária) e Espécie; Anual (1),Produção das principais culturas agrícolas (t) por Localização geográfica (Região agrária) e Espécie; Anual (1),Produtividade das principais culturas agrícolas (kg/ ha) por Localização geográfica (Região agrária) e Espécie; Anual (1)
0,2024,Portugal,Cereais para grão,191190.0,1008959.0,5277.0
1,2024,Portugal,Trigo,24107.0,78611.0,3261.0
2,2024,Portugal,Trigo mole,20303.0,65937.0,3248.0
3,2024,Portugal,Trigo duro,3805.0,12674.0,3331.0
4,2024,Portugal,Centeio,12744.0,12525.0,983.0
...,...,...,...,...,...,...
95,2024,Alentejo,Cereais para grão,79736.0,314579.0,3945.0
96,2024,Alentejo,Trigo,18362.0,68133.0,3710.0
97,2024,Alentejo,Trigo mole,14929.0,56136.0,3760.0
98,2024,Alentejo,Trigo duro,3433.0,11997.0,3494.0
99,2024,Alentejo,Centeio,189.0,327.0,1729.0

In [19]:
irr.head(100)

,Período de referência dos dados,Localização geográfica (Região agrária),Tipo de utilização das terras,Superfície irrigável (ha) das explorações agrícola por Localização geográfica (Região agrária) e Tipo de utilização das terras; Não periódica
0,2023,Portugal,Total,637339.0
1,2023,Portugal,Terra arável em cultura principal,272184.0
2,2023,Portugal,Culturas permanentes,325390.0
3,2023,Portugal,Pastagens permanentes,39765.0
4,2023,Alentejo,Total,265949.0
...,...,...,...,...
91,1999,Alentejo,Pastagens permanentes,NaN
92,1999,Algarve,Total,30012.0
93,1999,Algarve,Terra arável em cultura principal,NaN
94,1999,Algarve,Culturas permanentes,NaN
95,1999,Algarve,Pastagens permanentes,NaN

 ## Alterar os nomes das colunas

Prod

In [20]:
prod.columns = prod.columns.str.strip()

prod = prod.rename(columns={
    "Período de referência dos dados": "year",
    "Localização geográfica (Região agrária)": "region",
    "Espécie": "species",
    "Superfície das principais culturas agrícolas (ha) por Localização geográfica (Região agrária) e Espécie; Anual (1)": "area_ha",
    "Produção das principais culturas agrícolas (t) por Localização geográfica (Região agrária) e Espécie; Anual (1)": "production_t",
    "Produtividade das principais culturas agrícolas (kg/ ha) por Localização geográfica (Região agrária) e Espécie; Anual (1)": "productivity_kg_ha"
})

prod.head(100)

,year,region,species,area_ha,production_t,productivity_kg_ha
0,2024,Portugal,Cereais para grão,191190.0,1008959.0,5277.0
1,2024,Portugal,Trigo,24107.0,78611.0,3261.0
2,2024,Portugal,Trigo mole,20303.0,65937.0,3248.0
3,2024,Portugal,Trigo duro,3805.0,12674.0,3331.0
4,2024,Portugal,Centeio,12744.0,12525.0,983.0
...,...,...,...,...,...,...
95,2024,Alentejo,Cereais para grão,79736.0,314579.0,3945.0
96,2024,Alentejo,Trigo,18362.0,68133.0,3710.0
97,2024,Alentejo,Trigo mole,14929.0,56136.0,3760.0
98,2024,Alentejo,Trigo duro,3433.0,11997.0,3494.0
99,2024,Alentejo,Centeio,189.0,327.0,1729.0

irrigacao

In [21]:
irr.columns = irr.columns.str.strip()

irr = irr.rename(columns={
    "Período de referência dos dados": "year",
    "Localização geográfica (Região agrária)": "region",
    "Superfície irrigável (ha) das explorações agrícola por Localização geográfica (Região agrária) e Tipo de utilização das terras; Não periódica": "irrigable_area_ha",
    "Tipo de utilização das terras": "land_use_type"
})

irr.head()

   year    region                      land_use_type  irrigable_area_ha
0  2023  Portugal                              Total           637339.0
1  2023  Portugal  Terra arável em cultura principal           272184.0
2  2023  Portugal               Culturas permanentes           325390.0
3  2023  Portugal              Pastagens permanentes            39765.0
4  2023  Alentejo                              Total           265949.0

FILTRAR PROD

In [22]:
prod["year"] = prod["year"].astype(str).str[:4].astype(int)

Filtrar por ano e regiao

In [23]:
prod = prod[
    (prod["year"] >= 2000) &
    (prod["year"] <= 2018) &
    (prod["region"].isin(["Alentejo", "Algarve"]))
]

Verifica

In [25]:
prod.head()
prod["region"].value_counts()
prod["year"].min(), prod["year"].max()
prod.head(100)

,year,region,species,area_ha,production_t,productivity_kg_ha
1805,2018,Alentejo,Cereais para grão,99278.0,369821.0,3725.0
1806,2018,Alentejo,Trigo,18631.0,47839.0,2568.0
1807,2018,Alentejo,Trigo mole,14677.0,37133.0,2530.0
1808,2018,Alentejo,Trigo duro,3955.0,10706.0,2707.0
1809,2018,Alentejo,Centeio,112.0,134.0,1198.0
...,...,...,...,...,...,...
1900,2018,Algarve,Cereais para grão,2018.0,4327.0,2144.0
1901,2018,Algarve,Trigo,586.0,839.0,1432.0
1902,2018,Algarve,Trigo mole,484.0,677.0,1400.0
1903,2018,Algarve,Trigo duro,102.0,162.0,1584.0
1904,2018,Algarve,Centeio,13.0,12.0,870.0

FILTRAR IRRIGAÇÃO

converter ano

In [26]:
irr["year"] = irr["year"].astype(str).str[:4].astype(int)

Filtrar por ano e regiao

In [27]:

# Apply the filters for year and region
irr = irr[
    (irr["year"] >= 2000) &
    (irr["year"] <= 2020) &
    (irr["region"].isin(["Alentejo", "Algarve"]))
]

verificar

In [28]:
irr.head()
irr["region"].value_counts()
irr.tail(30)

    year    region                      land_use_type  irrigable_area_ha
42  2013  Alentejo               Culturas permanentes            87210.0
43  2013  Alentejo              Pastagens permanentes             8431.0
44  2013   Algarve                              Total            17269.0
45  2013   Algarve  Terra arável em cultura principal             2444.0
46  2013   Algarve               Culturas permanentes            14507.0
47  2013   Algarve              Pastagens permanentes              318.0
52  2009  Alentejo                              Total           155123.0
53  2009  Alentejo  Terra arável em cultura principal            71948.0
54  2009  Alentejo               Culturas permanentes            75553.0
55  2009  Alentejo              Pastagens permanentes             7622.0
56  2009   Algarve                              Total            16274.0
57  2009   Algarve  Terra arável em cultura principal             2199.0
58  2009   Algarve               Culturas permanentes            13416.0
59  2009   Algarve              Pastagens permanentes              659.0
64  2007  Alentejo                              Total           136856.0
65  2007  Alentejo  Terra arável em cultura principal            72271.0
66  2007  Alentejo               Culturas permanentes            55626.0
67  2007  Alentejo              Pastagens permanentes             8910.0
68  2007   Algarve                              Total            19663.0
69  2007   Algarve  Terra arável em cultura principal             3979.0
70  2007   Algarve               Culturas permanentes            15326.0
71  2007   Algarve              Pastagens permanentes              358.0
76  2005  Alentejo                              Total           140376.0
77  2005  Alentejo  Terra arável em cultura principal            94192.0
78  2005  Alentejo               Culturas permanentes            38762.0
79  2005  Alentejo              Pastagens permanentes             7422.0
80  2005   Algarve                              Total            24962.0
81  2005   Algarve  Terra arável em cultura principal             7659.0
82  2005   Algarve               Culturas permanentes            16387.0
83  2005   Algarve              Pastagens permanentes              916.0

In [29]:
irr_total = irr[
    irr["land_use_type"] == "Total"
].copy()

In [30]:
irr_total = irr_total[
    ["year", "region", "irrigable_area_ha"]
]

In [32]:
irr_total.head()

    year    region  irrigable_area_ha
16  2019  Alentejo           232627.0
20  2019   Algarve            22658.0
28  2016  Alentejo           175410.0
32  2016   Algarve            17158.0
40  2013  Alentejo           169573.0

In [33]:
irr_total.sort_values(["region", "year"])

    year    region  irrigable_area_ha
76  2005  Alentejo           140376.0
64  2007  Alentejo           136856.0
52  2009  Alentejo           155123.0
40  2013  Alentejo           169573.0
28  2016  Alentejo           175410.0
16  2019  Alentejo           232627.0
80  2005   Algarve            24962.0
68  2007   Algarve            19663.0
56  2009   Algarve            16274.0
44  2013   Algarve            17269.0
32  2016   Algarve            17158.0
20  2019   Algarve            22658.0

In [31]:
irr_total.groupby(["year", "region"]).size()

year  region
2005  Alentejo    1
      Algarve     1
2007  Alentejo    1
      Algarve     1
2009  Alentejo    1
      Algarve     1
2013  Alentejo    1
      Algarve     1
2016  Alentejo    1
      Algarve     1
2019  Alentejo    1
      Algarve     1
dtype: int64

## Garantir que os tipos estão corretos

In [34]:
irr_total["year"] = irr_total["year"].astype(int)

irr_total["irrigable_area_ha"] = pd.to_numeric(
    irr_total["irrigable_area_ha"],
    errors="coerce"
)

Criar uma linha para todos os anos (2000-2018)

In [35]:
years = range(2000, 2019)

irr_interp = []

for region in irr_total["region"].unique():

    temp = (
        irr_total[irr_total["region"] == region]
        .set_index("year")
        .reindex(years)
    )

    temp["region"] = region

    temp["irrigable_area_ha"] = (
        temp["irrigable_area_ha"]
        .interpolate(method="linear")
    )

    temp = (
        temp
        .reset_index()
        .rename(columns={"index": "year"})
    )

    irr_interp.append(temp)

irr_interp = pd.concat(
    irr_interp,
    ignore_index=True
)

In [36]:
irr_interp.head(25)

    year    region  irrigable_area_ha
0   2000  Alentejo                NaN
1   2001  Alentejo                NaN
2   2002  Alentejo                NaN
3   2003  Alentejo                NaN
4   2004  Alentejo                NaN
5   2005  Alentejo      140376.000000
6   2006  Alentejo      138616.000000
7   2007  Alentejo      136856.000000
8   2008  Alentejo      145989.500000
9   2009  Alentejo      155123.000000
10  2010  Alentejo      158735.500000
11  2011  Alentejo      162348.000000
12  2012  Alentejo      165960.500000
13  2013  Alentejo      169573.000000
14  2014  Alentejo      171518.666667
15  2015  Alentejo      173464.333333
16  2016  Alentejo      175410.000000
17  2017  Alentejo      175410.000000
18  2018  Alentejo      175410.000000
19  2000   Algarve                NaN
20  2001   Algarve                NaN
21  2002   Algarve                NaN
22  2003   Algarve                NaN
23  2004   Algarve                NaN
24  2005   Algarve       24962.000000

## Filtrar ambas as tabelas para 2005-2018

In [37]:
prod = prod[
    (prod["year"] >= 2005) &
    (prod["year"] <= 2018)
].copy()

irr_interp = irr_interp[
    (irr_interp["year"] >= 2005) &
    (irr_interp["year"] <= 2018)
].copy()

## Merge de prod com irr_interp

In [39]:
agri = pd.merge(
    prod,
    irr_interp,
    on=["year", "region"],
    how="left"
)

In [44]:
agri.tail(100)

,year,region,species,area_ha,production_t,productivity_kg_ha,irrigable_area_ha
2560,2005,Alentejo,Uva para vinho (Vinhos sem certificação),NaN,NaN,NaN,140376.0
2561,2005,Alentejo,Uva de mesa,378.0,3327.0,8811.0,140376.0
2562,2005,Alentejo,Olival,157076.0,61506.0,392.0,140376.0
2563,2005,Alentejo,Azeitona de mesa,2593.0,2388.0,921.0,140376.0
2564,2005,Alentejo,Azeitona para azeite,154483.0,59118.0,383.0,140376.0
...,...,...,...,...,...,...,...
2655,2005,Algarve,Uva para vinho (Vinhos sem certificação),NaN,NaN,NaN,24962.0
2656,2005,Algarve,Uva de mesa,1083.0,8521.0,7868.0,24962.0
2657,2005,Algarve,Olival,8905.0,2599.0,292.0,24962.0
2658,2005,Algarve,Azeitona de mesa,382.0,80.0,209.0,24962.0
2659,2005,Algarve,Azeitona para azeite,8523.0,2519.0,296.0,24962.0

In [46]:
agri = agri[agri["species"] != "Uva para vinho (Vinhos sem certificação)"]

In [49]:
agri.head(100)

,year,region,species,area_ha,production_t,productivity_kg_ha,irrigable_area_ha
0,2018,Alentejo,Cereais para grão,99278.0,369821.0,3725.0,175410.0
1,2018,Alentejo,Trigo,18631.0,47839.0,2568.0,175410.0
2,2018,Alentejo,Trigo mole,14677.0,37133.0,2530.0,175410.0
3,2018,Alentejo,Trigo duro,3955.0,10706.0,2707.0,175410.0
4,2018,Alentejo,Centeio,112.0,134.0,1198.0,175410.0
...,...,...,...,...,...,...,...
96,2018,Algarve,Trigo,586.0,839.0,1432.0,17158.0
97,2018,Algarve,Trigo mole,484.0,677.0,1400.0,17158.0
98,2018,Algarve,Trigo duro,102.0,162.0,1584.0,17158.0
99,2018,Algarve,Centeio,13.0,12.0,870.0,17158.0
100,2018,Algarve,Aveia,693.0,794.0,1145.0,17158.0

In [47]:
agri.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2632 entries, 0 to 2659
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                2632 non-null   int64
 1   region              2632 non-null   object
 2   species             2632 non-null   object
 3   area_ha             1682 non-null   float64
 4   production_t        1682 non-null   float64
 5   productivity_kg_ha  1404 non-null   float64
 6   irrigable_area_ha   2632 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 164.5+ KB

## se não há área → provavelmente não há cultivo

In [50]:
agri["area_ha"] = agri["area_ha"].fillna(0)

/tmp/ipykernel_22894/2130726969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agri["area_ha"] = agri["area_ha"].fillna(0)

## Produtividade só faz sentido ser 0 se área = 0

In [51]:
agri.loc[agri["area_ha"] == 0, "production_t"] = 0

## recalcular productivity_kg_ha

In [63]:
agri["productivity_kg_ha"] = (
    agri["production_t"] * 1000 / agri["area_ha"]
)

/tmp/ipykernel_22894/1298676182.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agri["productivity_kg_ha"] = (

In [64]:
agri.loc[agri["area_ha"] == 0, "productivity_kg_ha"] = 0

In [65]:
agri.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2632 entries, 0 to 2659
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                2632 non-null   int64
 1   region              2632 non-null   object
 2   species             2632 non-null   object
 3   area_ha             2632 non-null   float64
 4   production_t        2632 non-null   float64
 5   productivity_kg_ha  2632 non-null   float64
 6   irrigable_area_ha   2632 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 164.5+ KB

In [66]:
agri.to_csv(
    "agri_final.csv",
    index=False,
    encoding="utf-8-sig"
)

In [71]:
climate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              37 non-null     int64
 1   precipitation_mm  36 non-null     float64
 2   region            37 non-null     object
 3   mean_temp         37 non-null     float64
 4   mean_tmax         37 non-null     float64
 5   mean_tmin         37 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 1.9+ KB

In [74]:
climate[climate["precipitation_mm"].isna()]

    year  precipitation_mm   region  mean_temp  mean_tmax  mean_tmin
32  2014               NaN  Algarve  18.463333  22.436667  14.490833

In [75]:
climate.pivot_table(
    index="year",
    columns="region",
    values="precipitation_mm"
)

region  Alentejo  Algarve
year
2000       696.6    473.3
2001       669.8    692.7
2002       572.5    496.6
2003       587.0    522.7
2004       316.3    314.8
2005       339.1    368.0
2006       575.5    582.9
2007       349.8    400.3
2008       501.5    485.4
2009       483.8    504.6
2010       815.3    718.0
2011       656.8    536.7
2012       354.3    306.2
2013       443.5      NaN
2014       703.6      NaN
2015       415.0    343.0
2016       728.0    475.7
2017       434.1    316.1
2018       570.0    499.1

In [76]:
climate.pivot_table(
    index="year",
    columns="region",
    values="mean_temp"
)

region   Alentejo    Algarve
year
2000    16.958333  17.996667
2001    16.987500  18.151667
2002    16.895833  18.063333
2003    17.262500  18.254167
2004    17.191667  18.102500
2005    17.116667  17.800833
2006    17.382500  18.284167
2007    16.683333  17.945000
2008    16.484167  17.827500
2009    17.556667  18.386667
2010    17.114167  18.568333
2011    17.486667  18.880000
2012    16.707500  18.208333
2013    16.858333        NaN
2014    17.575000  18.463333
2015    18.022500  18.776667
2016    17.429167  18.866667
2017    18.050833  18.641818
2018    16.590000  17.950000

In [77]:
climate["precipitation_mm"] = (
    climate.groupby("region")["precipitation_mm"]
    .transform(lambda x: x.interpolate(method="linear"))
)

In [78]:
climate["mean_temp"] = (
    climate.groupby("region")["mean_temp"]
    .transform(lambda x: x.interpolate(method="linear"))
)

In [79]:
climate["mean_tmax"] = (
    climate.groupby("region")["mean_tmax"]
    .transform(lambda x: x.interpolate(method="linear"))
)

climate["mean_tmin"] = (
    climate.groupby("region")["mean_tmin"]
    .transform(lambda x: x.interpolate(method="linear"))
)

In [80]:
climate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              37 non-null     int64
 1   precipitation_mm  37 non-null     float64
 2   region            37 non-null     object
 3   mean_temp         37 non-null     float64
 4   mean_tmax         37 non-null     float64
 5   mean_tmin         37 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 1.9+ KB

In [86]:
climate.isna().sum()

year                0
precipitation_mm    0
region              0
mean_temp           0
mean_tmax           0
mean_tmin           0
dtype: int64

## limpar strings escondidas

In [87]:
agri["region"] = agri["region"].str.strip()
climate["region"] = climate["region"].str.strip()

/tmp/ipykernel_22894/4272884442.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agri["region"] = agri["region"].str.strip()

## garantir mesmo formato de ano

In [88]:
agri["year"] = agri["year"].astype(int)
climate["year"] = climate["year"].astype(int)

/tmp/ipykernel_22894/3103283257.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  agri["year"] = agri["year"].astype(int)

In [81]:
final_df = pd.merge(
    agri,
    climate,
    on=["year", "region"],
    how="left"
)

In [89]:
print(agri["region"].unique())
print(climate["region"].unique())

['Alentejo' 'Algarve']
['Alentejo' 'Algarve']

In [90]:
set(agri[["year", "region"]].apply(tuple, axis=1)).intersection(
    set(climate[["year", "region"]].apply(tuple, axis=1))
)

{(2005, 'Alentejo'),
 (2005, 'Algarve'),
 (2006, 'Alentejo'),
 (2006, 'Algarve'),
 (2007, 'Alentejo'),
 (2007, 'Algarve'),
 (2008, 'Alentejo'),
 (2008, 'Algarve'),
 (2009, 'Alentejo'),
 (2009, 'Algarve'),
 (2010, 'Alentejo'),
 (2010, 'Algarve'),
 (2011, 'Alentejo'),
 (2011, 'Algarve'),
 (2012, 'Alentejo'),
 (2012, 'Algarve'),
 (2013, 'Alentejo'),
 (2014, 'Alentejo'),
 (2014, 'Algarve'),
 (2015, 'Alentejo'),
 (2015, 'Algarve'),
 (2016, 'Alentejo'),
 (2016, 'Algarve'),
 (2017, 'Alentejo'),
 (2017, 'Algarve'),
 (2018, 'Alentejo'),
 (2018, 'Algarve')}

In [108]:
climate = climate.sort_values(["region", "year"])

climate["precipitation_mm"] = climate.groupby("region")["precipitation_mm"].transform(lambda x: x.interpolate())

climate["mean_temp"] = climate.groupby("region")["mean_temp"].transform(lambda x: x.interpolate())

climate["mean_tmax"] = climate.groupby("region")["mean_tmax"].transform(lambda x: x.interpolate())

climate["mean_tmin"] = climate.groupby("region")["mean_tmin"].transform(lambda x: x.interpolate())

In [109]:
print("Climate data for 2013, Algarve before merge (after fixing climate creation):")
print(climate[(climate["year"] == 2013) & (climate["region"] == "Algarve")])

final_df = agri.merge(
    climate,
    on=["year", "region"],
    how="left"
)

Climate data for 2013, Algarve before merge (after fixing climate creation):
    year  precipitation_mm   region  mean_temp  mean_tmax  mean_tmin
27  2013        318.466667  Algarve  18.198333  22.055833  14.341667

In [110]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2632 entries, 0 to 2631
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                2632 non-null   int64
 1   region              2632 non-null   object
 2   species             2632 non-null   object
 3   area_ha             2632 non-null   float64
 4   production_t        2632 non-null   float64
 5   productivity_kg_ha  2632 non-null   float64
 6   irrigable_area_ha   2632 non-null   float64
 7   precipitation_mm    2632 non-null   float64
 8   mean_temp           2632 non-null   float64
 9   mean_tmax           2632 non-null   float64
 10  mean_tmin           2632 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 226.3+ KB

In [111]:
final_df.to_csv(
    "agroclimate_final.csv",
    index=False,
    encoding="utf-8-sig"
)